const kantoPokemon = [
    'bulbasaur', 'ivysaur', 'venusaur', 'charmander', 'charmeleon',
    'charizard', 'squirtle', 'wartortle', 'blastoise', 'caterpie',
    'metapod', 'butterfree', 'weedle', 'kakuna', 'beedrill',
    'pidgey', 'pidgeotto', 'pidgeot', 'rattata', 'raticate',
    'spearow', 'fearow', 'ekans', 'arbok', 'pikachu',
    'raichu', 'sandshrew', 'sandslash', 'nidoran-f', 'nidorina',
    'nidoqueen', 'nidoran-m', 'nidorino', 'nidoking', 'clefairy',
    'clefable', 'vulpix', 'ninetales', 'jigglypuff', 'wigglytuff',
    'zubat', 'golbat', 'oddish', 'gloom', 'vileplume',
    'paras', 'parasect', 'venonat', 'venomoth', 'diglett',
    'dugtrio', 'meowth', 'persian', 'psyduck', 'golduck',
    'mankey', 'primeape', 'growlithe', 'arcanine', 'poliwag',
    'poliwhirl', 'poliwrath', 'abra', 'kadabra', 'alakazam',
    'machop', 'machoke', 'machamp', 'bellsprout', 'weepinbell',
    'victreebel', 'tentacool', 'tentacruel', 'geodude', 'graveler',
    'golem', 'ponyta', 'rapidash', 'slowpoke', 'slowbro',
    'magnemite', 'magneton', 'farfetchd', 'doduo', 'dodrio',
    'seel', 'dewgong', 'grimer', 'muk', 'shellder',
    'cloyster', 'gastly', 'haunter', 'gengar', 'onix',
    'drowzee', 'hypno', 'krabby', 'kingler', 'voltorb',
    'electrode', 'exeggcute', 'exeggutor', 'cubone', 'marowak',
    'hitmonlee', 'hitmonchan', 'lickitung', 'koffing', 'weezing',
    'rhyhorn', 'rhydon', 'chansey', 'tangela', 'kangaskhan',
    'horsea', 'seadra', 'goldeen', 'seaking', 'staryu',
    'starmie', 'mr. mime', 'scyther', 'jynx', 'electabuzz',
    'magmar', 'pinsir', 'tauros', 'magikarp', 'gyarados',
    'lapras', 'ditto', 'eevee', 'vaporeon', 'jolteon',
    'flareon', 'porygon', 'omanyte', 'omastar', 'kabuto',
    'kabutops', 'aerodactyl', 'snorlax', 'articuno', 'zapdos',
    'moltres', 'dratini', 'dragonair', 'dragonite', 'mewtwo',
    'mew'
];


const evolution = [
    true, true, false, true, true,
    false, true, true, false, true,
    true, false, true, true, false,
    true, true, false, true, false,
    true, false, true, false, true,
    false, true, false, true, true,
    false, true, true, false, true,
    false, true, false, true, false,
    true, false, true, true, false,
    true, false, true, false, true,
    false, true, false, true, false,
    true, false, true, false, true,
    true, false, true, true, false,
    true, true, false, true, true,
    false, true, false, true, true,
    false, true, false, true, false,
    true, false, false, true, false,
    true, false, true, false, true,
    false, true, true, false, false,
    true, false, true, false, true,
    false, true, false, true, false,
    false, false, false, true, false,
    true, false, false, false, false,
    true, false, true, false, true,
    false, false, false, false, false,
    false, false, false, true, false,
    false, false, true, false, false,
    false, false, true, false, true,
    false, false, false, false, false,
    false, true, true, false, false,
    false
];


const typeColor = {
    'normal': '#BBBBAA',
    'fire': '#FF421C',
    'water': '#2C9BE3',
    'electric': '#FFDC00',
    'grass': '#62BC5A',
    'flying': '#96CAFF',
    'bug': '#92C12A',
    'poison': '#9553CD',
    'rock': '#BBAA66',
    'ground': '#A67439',
    'fighting': '#BB5544',
    'ice': '#74CFC0',
    'psychic': '#FF6380',
    'ghost': '#6E4370',
    'dragon': '#5670BE',
    'dark': '#4E4545',
    'steel': '#AAAABB',
    'fairy': '#EC8FE6'
}

// option: German names
// option: more Pokemon